---
services:
  ultimoteste:
    build: 
      context: ../
      dockerfile: ./docker/Dockerfile
    container_name: ultimoteste
    networks:
      - traefik
    labels:      
      - traefik.enable=true
      - traefik.http.routers.ultimoteste.entrypoints=web
      - traefik.http.routers.ultimoteste.service=noop@internal
      - traefik.http.routers.ultimoteste.middlewares=redirect-to-https@file
      
      - traefik.http.routers.ultimoteste-https.tls=true
      - traefik.http.routers.ultimoteste-https.service=ultimoteste
      - traefik.http.routers.ultimoteste-https.entrypoints=websecure
      - traefik.http.services.ultimoteste.loadbalancer.server.port=8080

      - traefik.http.routers.ultimoteste-https.tls.certresolver=production
      - traefik.http.routers.ultimoteste-https.tls.domains[0].main=vps2.medeirosdev.com.br
      - "traefik.http.routers.ultimoteste-https.tls.domains[0].sans=*.vps2.medeirosdev.com.br"

networks:
  traefik:
    external: true